# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Inicio
    url: '/'
    weight: 10
    
  - name: Nomenclatura
    weight: 20
    identifier: nomenclatura
    
  - name: Nomenclatura inorg치nica
    PageRef: course/example_1/_index.md
    weight: 30
    parent: nomenclatura
    
  - name: Nomenclatura org치nica
    PageRef: course/example_2/_index.md
    weight: 40
    parent: nomenclatura
    
  - name: Blog
    PageRef: post/_index.md
    weight: 50
    
  - name: Mis libros
    PageRef: contact/index.md
    weight: 60
    
  - name: Nomenclatura2
    weight: 20
    identifier: nomenclatura2
    
  - name: Nomenclatura inorg치nica2
    PageRef: otros_cont/fisica/_index.md
    weight: 30
    parent: nomenclatura2

  - name: Nomenclatura org치nica
    PageRef: otros_cont/quimica/_index.md
    weight: 40
    parent: nomenclatura2

    

    

    
